### ISSUE TITLE
[Error] Awwesome container throws error - shows only standard nginx welcome page

### ISSUE THREAD

**Issue by GFNiko** [mkitzmann/awwesome#11]
Error Message:
```
transforming...

src/lib/fetch-github.ts (1:9) "GithubQueryResult" is not exported by "src/lib/types/types.ts", imported by "src/lib/fetch-github.ts".

src/lib/fetch-github.ts (1:28) "GithubRepo" is not exported by "src/lib/types/types.ts", imported by "src/lib/fetch-github.ts".

✓ 99 modules transformed.

rendering chunks...

creating entries function

node:internal/event_target:1054

  process.nextTick(() => { throw err; });

                           ^

TypeError [Error]: fetch failed

    at fetch (/usr/src/app/node_modules/undici/index.js:109:13)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async combineSources (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:188:22)

    at async getAllCategories (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:205:20)

    at async entries (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:258:27)

    at async analyse (file:///usr/src/app/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js:148:17)

    at async MessagePort.<anonymous> (file:///usr/src/app/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)

Emitted 'error' event on Worker instance at:

    at [kOnErrorMessage] (node:internal/worker:326:10)

    at [kOnMessage] (node:internal/worker:337:37)

    at MessagePort.<anonymous> (node:internal/worker:232:57)

    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:778:20)
```

.env: `TOKEN_GITHUB={{ token from github.com }}`

docker-compose.yml
```
version: '3'
services:
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: awwesome_ofelia
    depends_on:
      - source
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.awwesome.schedule: "@daily"
      ofelia.job-run.awwesome.container: "awwesome"

  source:
    image: mkitzmann/awwesome
    container_name: awwesome
    env_file:
      - .env
    working_dir: /usr/src/app
    command: sh -c "npm run build && rm -r html/* && cp -r dist/* html && exit"
    volumes:
      - shared_volume:/usr/src/app/html

  web:
    image: nginx
    container_name: awwesome_nginx
    ports: 
      - 7880:80
    volumes:
      - shared_volume:/usr/share/nginx/html:ro

volumes:
  shared_volume:

```

portainer shows github token as a environment variable:
![image](https://github.com/mkitzmann/awwesome/assets/114079308/cb51611f-e182-4ad2-9312-99781c711176)

Tried to set up the containers with minor differences in docker.-compose file. For example in bdridge mode. didn't change anything
